// reposConfig.groovy
return [
    [name: 'ie-global', param: 'IE_GLOBAL_BRANCH', cmd: "mvn -U -P '!tag' clean install"],
    [name: 'ie-deps', param: 'IE_DEPS_BRANCH', cmd: "mvn -U -P '!tag' clean install"],
    [name: 'ips-bo-api-specs', param: 'IPS_BO_API_SPECS_BRANCH', cmd: "mvn -U -P '!tag' -DskipTests clean install"],
    [name: 'ips-tch-backoffice', param: 'IPS_TCH_BACKOFFICE_BRANCH', cmd: "mvn -U -P '!tag,rpm,war' -DskipTests clean install"],
    [name: 'ips-dsp', param: 'IPS_DSP_BRANCH', cmd: "mvn -U -P rpm -P '!tag' -DskipTests clean install"],
    [name: 'ips-messages-canonical', param: 'IPS_MESSAGES_CANONICAL_BRANCH', cmd: "mvn -U -P '!tag' -DskipTests clean install"],
    [name: 'ips-messages-iso20022', param: 'IPS_MESSAGES_ISO20022_BRANCH', cmd: "mvn -U -P '!tag' -DskipTests clean install"],
    [name: 'maps-service-config', param: 'MAPS_SERVICE_CONFIG_BRANCH', cmd: "mvn -U -P '!tag' -DskipTests clean install"],
    [name: 'ips-maps-core', param: 'IPS_MAPS_CORE_BRANCH', cmd: "mvn -U -P '!tag,rpm' -DskipTests clean install"],
    [name: 'ips-tch-database', param: 'IPS_TCH_DATABASE_BRANCH', cmd: "mvn -U -P rpm,war -DskipTests clean install"],
    [name: 'ips-tch-msimui', param: 'IPS_TCH_MSIMUI_BRANCH', cmd: "mvn -U -P '!tag,rpm' -DskipTests clean install"],
    [name: 'ips-tch-switch', param: 'IPS_TCH_SWITCH_BRANCH', cmd: "./build.sh"],
    [name: 'ips-tch-transformer', param: 'IPS_TCH_TRANSFORMER_BRANCH', cmd: "mvn -U -P '!tag,rpm' -DskipTests clean install"],
    [name: 'ips-transformer', param: 'IPS_TRANSFORMER_BRANCH', cmd: "mvn -U -P '!tag' -DskipTests clean install"],
    [name: 'maps-tch', param: 'MAPS_TCH_BRANCH', cmd: "mvn -U -P '!tag' -DskipTests clean install"],
    [name: 'rambus-ste-client', param: 'RAMBUS_STE_CLIENT_BRANCH', cmd: "mvn -U -P '!tag' -DskipTests clean install"],
    [name: 'db', param: 'DB_BRANCH', cmd: "mvn -U -P '!tag' clean install"],
    [name: 'bo', param: 'BO_BRANCH', cmd: "mvn -U -P '!tag' clean install"],
    [name: 'opsui', param: 'OPSUI_BRANCH', cmd: "mvn -U -P '!tag' clean install"],
    [name: 'liability-manager', param: 'LIABILITY_MANAGER_BRANCH', cmd: "mvn -U -P '!tag' clean install"],
    [name: 'maps-dsp', param: 'MAPS_DSP_BRANCH', cmd: "mvn -U -P '!tag' clean install"],
    [name: 'legacy-dsp', param: 'LEGACY_DSP_BRANCH', cmd: "mvn -U -P '!tag' clean install"],
    [name: 'sachsim-ui', param: 'SACHSIM_UI_BRANCH', cmd: "mvn -U -P '!tag' clean install"],
    [name: 'legacy-transformer', param: 'LEGACY_TRANSFORMER_BRANCH', cmd: "mvn -U -P '!tag' clean install"],
    [name: 'is020022-tch-version', param: 'IS020022_TCH_VERSION_BRANCH', cmd: "mvn -U -P '!tag' clean install"]
]
